### ISSUE TITLE
Single event error when k = self._argmax = 2

### ISSUE THREAD

**Issue by rosskempner** [lgeerligs/statesegmentation#1]
Hello,

Note that the following is keeping in mind the source code file gsbs.py, which I have placed my pdb debugger in to see what is going on. 

I am looking inside the get_states function to see why this occured.

When k = 2, then self.get_deltas(k) returns the following: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Notice above how there is no 1 in there to indicate an event boundary.

Then, the self._states(self.get_deltas(k), self.x)+1 returns array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) as we'd expect

When investigating this further, I found that self.all_bounds[2] is a vector of all 0's like this: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Note that when k number of states is > 2 in the argment to get_states function, then things look as we'd expect. 

I may have found the culprit of the error in the gsbs.py file. In the fit function, should it be `k >= 2` instead of` k > 2`?

```
            if self.finetune != 0 and k > 2:
                self._bounds = self._finetune(self._bounds, self.x, z, self.finetune)
                self._deltas=self._bounds>0
                self.all_bounds[k]=self._bounds

```

When changing to `k >= 2`, things seem to work well when we have 2 events as the self._argmax but I want to double check with you that changing to `k >= 2` does not mess anything up? 

Best wishes,Ross

**Comment by lgeerligs** [comment]
Dear Ross,

Thank you for spotting this error!
I will try to fix it as soon as possible.

Best,
Linda

Op vr 27 aug. 2021 om 19:39 schreef rosskempner ***@***.***>:

**Comment by rosskempner** [comment]
Thanks Linda! :)
